pathogen_name_maps_dict = {
    # Streptococcen Pathogens
    'Streptococcen Gruppe B / S. agalactiae': 'Group B Streptococci', 
    'Streptococcen Gruppe A / S. pyogenes': 'Group A Streptococci', 
    'Streptococcen Gruppe C': 'Group C Streptococci',
    'Streptococcen Gruppe D': 'Group D Streptococci', 
    'Streptococcen Gruppe E': 'Group E Streptococci',
    'Streptococcen Gruppe F': 'Group F Streptococci',
    'Streptococcen Gruppe G': 'Group G Streptococci',
    'Streptococcen (beta-hämolysierend)': 'Beta-hemolytic Streptococci', 
    'Streptococcen alpha-hämolysierend / Viridansgruppe': 'Alpha-hemolytic Streptococci',
    'Streptococcen (nicht hämolysierend)': 'Non-hemolytic Streptococci', 
    'Streptococcen (gamma-hämolysierend)': 'Gamma-hemolytic Streptococci', 
    # Enterobacterales
    'Klebsiella (früher: Enterobacter) aerogenes': 'Klebsiella aerogenes',
    'Enterobacter hormaechei': 'Enterobacter hormaechei',
    'Enterobacter cloacae': 'Enterobacter cloacae',
    'Enterobacter spp.': 'Enterobacter spp.',
    'Enterobacter asburiae': 'Enterobacter asburiae',
    'Enterobacter cancerogenus': 'Enterobacter cancerogenus',
    'Enterobacter intermedium': 'Enterobacter intermedium',
    'Enterobacterales (früher: Enterobacteriaceae)': 'Enterobacterales',
    'Enterobacter kobei': 'Enterobacter kobei',
    'Enterobacter ludwigii': 'Enterobacter ludwigii',
    'Enterobacter taylorae': 'Enterobacter taylorae',
    # Acinetobacter Family 
    'Acinetobacter baumannii complex': 'Acinetobacter baumannii',
    'Acinetobacter lwoffi': 'Acinetobacter lwoffii',
    'Acinetobacter johnsonii': 'Acinetobacter johnsonii',
    'Acinetobacter junii': 'Acinetobacter junii',
    'Acinetobacter spp.': 'Acinetobacter spp.',
    'Acinetobacter ursingii': 'Acinetobacter ursingii',
    'Acinetobacter haemolyticus': 'Acinetobacter haemolyticus',
    'Acinetobacter radioresistens': 'Acinetobacter radioresistens',
    'Acinetobacter calcoaceticus': 'Acinetobacter calcoaceticus',
    'Acinetobacter bereziniae': 'Acinetobacter bereziniae',
    'Acinetobacter guillouiae': 'Acinetobacter guillouiae',
    'Acinetobacter parvus': 'Acinetobacter parvus',
    'Acinetobacter schindleri': 'Acinetobacter schindleri',
    'Acinetobacter gyllenbergii': 'Acinetobacter gyllenbergii',
    'Acinetobacter beijerinckii': 'Acinetobacter beijerinckii',
    'Acinetobacter baylyi': 'Acinetobacter baylyi',
    # Salmonella
    'Salmonella oranienburg': 'Salmonella Oranienburg',
    'Salmonella Gruppe B': 'Salmonella Group B',
    'Salmonella typhimurium': 'Non-typhoidal Salmonella',
    'Salmonella montevideo': 'Salmonella Montevideo',
    'Salmonella enteritidis': 'Salmonella Enteritidis',
    'Salmonella stanley': 'Salmonella Stanley',
    'Salmonella muenchen': 'Salmonella München',
    'Salmonella spp.': 'Salmonella spp.',
    'Salmonella enterica': 'Salmonella Enterica',
    'Salmonella kentucky': 'Salmonella Kentucky',
    'Salmonella berta': 'Salmonella Berta',
    'Salmonella Gruppe C': 'Salmonella Group C',
    'Salmonella infantis': 'Salmonella Infantis',
    'Salmonella typhi': 'Salmonella Typhi',
    'Salmonella derby': 'Salmonella Derby',
    'Salmonella goldcoast': 'Salmonella Goldcoast',
    'Salmonella Gruppe D': 'Salmonella Group D',
    'Salmonella indiana': 'Salmonella Indiana',
    'Salmonella braenderup': 'Salmonella Braenderup',
    'Salmonella Gruppe E': 'Salmonella Group E',
    'Salmonella agona': 'Salmonella Agona',
    'Salmonella newport': 'Salmonella Newport',
    'Salmonella heidelberg': 'Salmonella Heidelberg',
    'Salmonella muenster': 'Salmonella Münster',
    'Salmonella chester': 'Salmonella Chester',
    'Salmonella give': 'Salmonella Give',
    'Salmonella paratyphi B': 'Salmonella Paratyphi B',
    'Salmonella choleraesuis': 'Salmonella Choleraesuis',
    'Salmonella blockley': 'Salmonella Blockley',
    'Salmonella bredeney': 'Salmonella Bredeney',
    'Salmonella bovis morbificans': 'Salmonella Bovis Morbificans',
    'Salmonella Gruppe A': 'Salmonella Group A',
    'Salmonella brandenburg': 'Salmonella Brandenburg',
    'Salmonella cottbus': 'Salmonella Cottbus',
    'Salmonella saint-paul': 'Salmonella Saint-Paul',
    'Salmonella london': 'Salmonella London',
    'Salmonella paratyphi A': 'Salmonella Paratyphi A',
    'Salmonella virchow': 'Salmonella Virchow',
    'Salmonella livingstone': 'Salmonella Livingstone',
    'Salmonella amsterdam': 'Salmonella Amsterdam',
    'Salmonella weltevreden': 'Salmonella Weltevreden',
    'Salmonella thompson': 'Salmonella Thompson',
    'Salmonella hadar': 'Salmonella Hadar',
    'Salmonella havana': 'Salmonella Havana',
    'Salmonella cerro': 'Salmonella Cerro',
    'Salmonella enterica ssp enterica': 'Salmonella Enterica ssp. Enterica',
    # Shigella
    'Shigella spp.': 'Shigella spp.',
    'Shigella flexneri': 'Shigella flexneri',
    'Shigella dysenteriae': 'Shigella dysenteriae',
    'Shigella boydii': 'Shigella boydii',
    'Shigella sonnei': 'Shigella sonnei',
    # Enterococcus
    'Enterococcus faecalis': 'Enterococcus faecalis',
    'Enterococcus avium': 'Enterococcus avium',
    'Enterococcus durans': 'Enterococcus durans',
    'Enterococcus faecium': 'Enterococcus faecium',
    'Enterococcus gallinarium': 'Enterococcus gallinarum',
    'Enterococcus spp.': 'Enterococcus spp.',
    'Enterococcus casseliflavus': 'Enterococcus casseliflavus',
    'Enterococcus hirae': 'Enterococcus hirae',
    'Enterococcus raffinosus': 'Enterococcus raffinosus',
    'Enterococcus hirea': 'Enterococcus hirae',
    'Enterococcus mundtii': 'Enterococcus mundtii',
    'Enterococcus malodoratus': 'Enterococcus malodoratus',
    'Enterococcus thailandicus': 'Enterococcus thailandicus',
    'Enterococcus gilvus': 'Enterococcus gilvus',
    'Enterococcus canintestini': 'Enterococcus canintestini',
    'Enterococcus cecorum': 'Enterococcus cecorum',
    # Neisseria gonorrhoeae
    'Neisseria gonorrhoeae': 'Neisseria gonorrhoeae',
    # Staphylococcus
    'Staphylococcus pettenkoferi': 'Staphylococcus pettenkoferi',
    'Staphylococcus aureus': 'Staphylococcus aureus',
    'Staphylococcus epidermidis': 'Staphylococcus epidermidis',
    'Staphylococcus lugdunensis': 'Staphylococcus lugdunensis',
    'Staphylococcus pasteuri': 'Staphylococcus pasteuri',
    'Staphylococcus condimenti': 'Staphylococcus condimenti',
    'Staphylococcus spp.': 'Staphylococcus spp.',
    'Staphylococcus saprophyticus': 'Staphylococcus saprophyticus',
    'Staphylococcus capitis': 'Staphylococcus capitis',
    'Staphylococcus haemolyticus': 'Staphylococcus haemolyticus',
    'Staphylococcus auricularis': 'Staphylococcus auricularis',
    'Staphylococcus caprae': 'Staphylococcus caprae',
    'Staphylococcus warneri': 'Staphylococcus warneri',
    'Staphylococcus hominis': 'Staphylococcus hominis',
    'Staphylococcus simulans': 'Staphylococcus simulans',
    'Staphylococcus intermedius': 'Staphylococcus intermedius',
    'Staphylococcus saccharolyticus': 'Staphylococcus saccharolyticus',
    'Staphylococcus piscifermentans': 'Staphylococcus piscifermentans',
    'Staphylococcus nepalensis': 'Staphylococcus nepalensis',
    'Staphylococcus schleiferi': 'Staphylococcus schleiferi',
    'Staphylococcus cohnii': 'Staphylococcus cohnii',
    'Staphylococcus sciuri': 'Staphylococcus sciuri',
    'Staphylococcus vitulinus': 'Staphylococcus vitulinus',
    'Staphylococcus lentus': 'Staphylococcus lentus',
    'Staphylococcus equorum': 'Staphylococcus equorum',
    'Staphylococcus pseudintermedius': 'Staphylococcus pseudintermedius',
    'Staphylococcus xylosus': 'Staphylococcus xylosus',
    'Staphylococcus felis': 'Staphylococcus felis',
    'Staphylococcus urealyticum': 'Staphylococcus urealyticum',
    'Staphylococcus cohnii ssp urealyticus': 'Staphylococcus cohnii ssp. urealyticus',
    'Staphylococcus carnosus': 'Staphylococcus carnosus',
    'Staphylococcus chromogenes': 'Staphylococcus chromogenes',
    'Staphylococcus hominis ssp novobiosepticus': 'Staphylococcus hominis ssp. novobiosepticus',
    'Staphylococcus kloosii': 'Staphylococcus kloosii',
    'Staphylococcus gallinarium': 'Staphylococcus gallinarium',
    'Staphylococcus arlettae': 'Staphylococcus arlettae',
    'Staphylococcus gallinarum': 'Staphylococcus gallinarum',
    'Staphylococcus hyicus': 'Staphylococcus hyicus',
    # Streptococcus
    'Streptococcus constellatus': 'Streptococcus constellatus',
    'Streptococcus anginosus': 'Streptococcus anginosus',
    'Streptococcus dysgalactiae': 'Streptococcus dysgalactiae',
    'Streptococcus vestibularis': 'Streptococcus vestibularis',
    'Streptococcus mitis': 'Streptococcus mitis',
    'Streptococcus intermedius': 'Streptococcus intermedius',
    'Streptococcus oralis': 'Streptococcus oralis',
    'Streptococcus salivarius': 'Streptococcus salivarius',
    'Streptococcus parasanguinis': 'Streptococcus parasanguinis',
    'Peptostreptococcus spp.': 'Peptostreptococcus spp.',
    'Streptococcus gallolyticus': 'Streptococcus gallolyticus',
    'Streptococcus spp.': 'Streptococcus spp.',
    'Streptococcus sanguinis': 'Streptococcus sanguinis',
    'Streptococcus pneumoniae': 'Streptococcus pneumoniae',
    'Peptostreptococcus magnus': 'Peptostreptococcus magnus',
    'Streptococcus equi ssp zooepidemicus': 'Streptococcus equi ssp. zooepidemicus',
    'Peptostreptococcus anaerobius': 'Peptostreptococcus anaerobius',
    'Streptococcus lutetiensis': 'Streptococcus lutetiensis',
    'Streptococcus bovis': 'Streptococcus bovis',
    'Streptococcus urinalis': 'Streptococcus urinalis',
    'Streptococcus gordonii': 'Streptococcus gordonii',
    'Streptococcus thermophilus': 'Streptococcus thermophilus',
    'Streptococcus mutans': 'Streptococcus mutans',
    'Streptococcus infantarius': 'Streptococcus infantarius',
    'Streptococcus equisimilis': 'Streptococcus equisimilis',
    'Streptococcus pasteurianus': 'Streptococcus pasteurianus',
    'Streptococcus equinus': 'Streptococcus equinus',
    'Streptococcus zooepidemicus': 'Streptococcus zooepidemicus',
    'Streptococcus canis': 'Streptococcus canis',
    'Streptococcus alactolyticus': 'Streptococcus alactolyticus',
    'Streptococcus cristatus': 'Streptococcus cristatus',
    'Streptococcus suis': 'Streptococcus suis',
    'Streptococcus constellatus ssp pharyngis': 'Streptococcus constellatus ssp. pharyngis',
    'Streptococcus uberis': 'Streptococcus uberis',
    'Peptostreptococcus hydrogenalis': 'Peptostreptococcus hydrogenalis',
    'Streptococcus thoraltensis': 'Streptococcus thoraltensis',
    'Streptococcus porcinus': 'Streptococcus porcinus',
    'Streptococcus pseudopneumoniae': 'Streptococcus pseudopneumoniae',
    'Streptococcus massiliensis': 'Streptococcus massiliensis',
    'Streptococcus ovis': 'Streptococcus ovis',
    'Streptococcus pseudoporcinus': 'Streptococcus pseudoporcinus',
    'Streptococcus gallolyticus ssp pasteurianus': 'Streptococcus gallolyticus ssp. pasteurianus',
    'Streptococcus infantis': 'Streptococcus infantis',
    'Peptostreptococcus tetradium': 'Peptostreptococcus tetradium',
    'Streptococcus equi': 'Streptococcus equi',
    'Streptococcus peroris': 'Streptococcus peroris',
    'Streptococcus sobrinus': 'Streptococcus sobrinus',
    'Streptococcus parvulus': 'Streptococcus parvulus',
    'Streptococcus acidominimus': 'Streptococcus acidominimus',
    'Streptococcus minor': 'Streptococcus minor',
    # Haemophilus
    'Haemophilus influenzae': 'Haemophilus influenzae',
    'Haemophilus parainfluenzae': 'Haemophilus parainfluenzae',
    'Haemophilus parahaemolyticus': 'Haemophilus parahaemolyticus',
    'Haemophilus haemolyticus': 'Haemophilus haemolyticus',
    'Haemophilus spp.': 'Haemophilus spp.',
    'Haemophilus sputorum': 'Haemophilus sputorum',
    'Haemophilus paraphrohaemolyticus': 'Haemophilus paraphrohaemolyticus',
    'Haemophilus pittmaniae': 'Haemophilus pittmaniae',
    'Haemophilus haemoglobinophilus': 'Haemophilus haemoglobinophilus',
    'Haemophilus parphrophilus': 'Haemophilus paraphrophilus',
    # Pseudomonas
    'Pseudomonas fluorescens': 'Pseudomonas fluorescens',
    'Pseudomonas aeruginosa': 'Pseudomonas aeruginosa',
    'Pseudomonas aureofaciens': 'Pseudomonas aureofaciens',
    'Pseudomonas spp.': 'Pseudomonas spp.',
    'Pseudomonas oleovorans': 'Pseudomonas oleovorans',
    'Pseudomonas putida': 'Pseudomonas putida',
    'Pseudomonas stutzeri': 'Pseudomonas stutzeri',
    'Pseudomonas alcaligenes': 'Pseudomonas alcaligenes',
    'Pseudomonas mendocina': 'Pseudomonas mendocina',
    'Pseudomonas mosselii': 'Pseudomonas mosselii',
    'Pseudomonas pseudoalcaligenes': 'Pseudomonas pseudoalcaligenes',
    'Pseudomonas fulva': 'Pseudomonas fulva',
    'Pseudomonas citronellolis': 'Pseudomonas citronellolis',
    'Pseudomonas chlororaphis': 'Pseudomonas chlororaphis',
    'Pseudomonas monteilii': 'Pseudomonas monteilii',
    'Pseudomonas proteolytica': 'Pseudomonas proteolytica',
    'Pseudomonas synxantha': 'Pseudomonas synxantha',
    'Pseudomonas fragi': 'Pseudomonas fragi',
    'Pseudomonas rhodesiae': 'Pseudomonas rhodesiae',
    'Pseudomonas graminis': 'Pseudomonas graminis',
    'Pseudomonas alcaliphila': 'Pseudomonas alcaliphila',
    'Pseudomonas plecoglossicida': 'Pseudomonas plecoglossicida',
    'Pseudomonas otitidis': 'Pseudomonas otitidis',
    'Pseudomonas guariconensis': 'Pseudomonas guariconensis',
    'Pseudomonas libanensis': 'Pseudomonas libanensis'
    
}




critical_pathogens = [
    "Enterobacterales", "Acinetobacter baumannii"
]

high_pathogens = [
    "Salmonella Typhi", "Shigella spp.", "Enterococcus faecium", "Pseudomonas aeruginosa", "Non-typhoidal Salmonella",
    "Neisseria gonorrhoeae", "Staphylococcus aureus"
]

medium_pathogens = [
    "Group A Streptococci", "Streptococcus pneumoniae", "Haemophilus influenzae", "Group B Streptococci"
]