state_mapping = {
    "Schleswig-Holstein": [
        "Flensburg, Stadt", 
        "Kiel, Landeshauptstadt", 
        "Lübeck, Hansestadt", 
        "Neumünster, Stadt", 
        "Dithmarschen",
        "Herzogtum Lauenburg",
        "Nordfriesland",
        "Ostholstein",
        "Pinneberg",
        "Plön",
        "Rendsburg-Eckernförde",
        "Schleswig-Flensburg",
        "Segeberg",
        "Steinburg",
        "Stormarn"

    ],
    "Mecklenburg-Vorpommern": [
        "Rostock, Stadt", 
        "Schwerin, Stadt",
        "Greifswald, Stadt",
        "Stralsund, Stadt",
        "Wismar, Stadt",
        "Ludwigslust-Parchim",
        "Mecklenburgische Seenplatte",
        "Rostock",
        "Landkreis Rostock",
        "Vorpommern-Greifswald",
        "Vorpommern-Rügen",
        "Schwerin",
        "Nordwestmecklenburg"

    ],
    "Hamburg": [
        "Hamburg, Stadt",
        "Hamburg, Freie und Hansestadt"

    ],
    "Niedersachsen": [
        "Hannover, Stadt", 
        "Region Hannover",
        "Delmenhorst, Stadt",
        "Emden, Stadt",
        "Braunschweig, Stadt", 
        "Oldenburg, Stadt", 
        "Oldenburg (Oldenburg), Stadt",
        "Wilhelmshaven, Stadt",
        "Grafschaft Bentheim",
        "Osnabrück, Stadt",
        "Salzgitter, Stadt",
        "Wolfsburg, Stadt",
        "Ammerland",
        "Aurich",
        "Cloppenburg",
        "Cuxhaven",
        "Celle",
        "Diepholz",
        "Emsland",
        "Friesland",
        "Gifhorn",
        "Goslar",
        "Göttingen",
        "Hameln-Pyrmont",
        "Harburg",
        "Heidekreis",
        "Helmstedt",
        "Hildesheim",
        "Holzminden",
        "Leer",
        "Lüchow-Dannenberg",
        "Lüneburg",
        "Nienburg (Weser)",
        "Northeim",
        "Oldenburg",
        "Osnabrück",
        "Osterholz",
        "Peine",
        "Rotenburg (Wümme)",
        "Schaumburg",
        "Stade",
        "Uelzen",
        "Vechta",
        "Verden",
        "Wesermarsch",
        "Wittmund",
        "Wolfenbüttel"
    ],
    "Bremen": [
        "Bremen, Stadt", 
        "Bremerhaven, Stadt",

    ],
    "Brandenburg": [
        "Potsdam, Stadt", 
        "Cottbus, Stadt", 
        "Brandenburg an der Havel, Stadt", 
        "Frankfurt (Oder), Stadt",
        "Barnim",
        "Dahme-Spreewald",
        "Elbe-Elster",
        "Havelland",
        "Märkisch-Oderland",
        "Oberhavel",
        "Oberspreewald-Lausitz",
        "Oder-Spree",
        "Ostprignitz-Ruppin",
        "Potsdam-Mittelmark",
        "Prignitz",
        "Spree-Neiße",
        "Teltow-Fläming",
        "Uckermark" 
    ],
    "Sachsen-Anhalt": [
        "Magdeburg, Stadt", 
        "Halle (Saale), Stadt",
        "Dessau-Roßlau, Stadt",
        "Altmarkkreis Salzwedel",
        "Anhalt-Bitterfeld",
        "Börde",
        "Magdeburg, Landeshauptstadt",
        "Burgenlandkreis",
        "Harz",
        "Jerichower Land",
        "Mansfeld-Südharz",
        "Saalekreis",
        "Salzlandkreis",
        "Stendal",
        "Wittenberg"
    ],
    "Berlin": [
        "Berlin, Stadt"
    ],
    "Nordrhein-Westfalen": [
        "Remscheid, Stadt",
        "Düsseldorf, Stadt", 
        "Köln, Stadt", 
        "Dortmund, Stadt", 
        "Krefeld, Stadt",
        "Leverkusen, Stadt",
        "Mönchengladbach, Stadt",
        "Mülheim an der Ruhr, Stadt",
        "Oberhausen, Stadt",
        "Solingen, Klingenstadt",
        "Rhein-Kreis Neuss",
        "Leverkusen, Stadt",
        "Städteregion Aachen",
        "Bottrop, Stadt",
        "Gelsenkirchen, Stadt",
        "Hagen, Stadt der FernUniversität",
        "Hamm, Stadt",
        "Ennepe-Ruhr-Kreis",
        "Herne, Stadt",
        "Essen, Stadt", 
        "Duisburg, Stadt",
        "Bochum, Stadt",
        "Wuppertal, Stadt",
        "Bielefeld, Stadt",
        "Bonn, Stadt",
        "Münster, Stadt",
        "Aachen, Stadt",
        "Borken",
        "Coesfeld",
        "Düren",
        "Ennepe-Ruhr-Kreis",
        "Euskirchen",
        "Gütersloh",
        "Heinsberg",
        "Herford",
        "Hochsauerlandkreis",
        "Höxter",
        "Kleve",
        "Lippe",
        "Märkischer Kreis",
        "Mettmann",
        "Minden-Lübbecke",
        "Oberbergischer Kreis",
        "Olpe",
        "Paderborn",
        "Recklinghausen",
        "Rhein-Erft-Kreis",
        "Rheinisch-Bergischer Kreis",
        "Rhein-Sieg-Kreis",
        "Siegen-Wittgenstein",
        "Soest",
        "Steinfurt",
        "Unna",
        "Viersen",
        "Warendorf",
        "Wesel"
    ],
    "Sachsen": [
        "Dresden, Stadt", 
        "Leipzig, Stadt", 
        "Chemnitz, Stadt",
        "Bautzen",
        "Erzgebirgskreis",
        "Görlitz",
        "Meißen",
        "Mittelsachsen",
        "Leipzig",
        "Nordsachsen",
        "Sächsische Schweiz-Osterzgebirge",
        "Vogtlandkreis",
        "Zwickau"
        
    ],
    "Hessen": [
        "Wiesbaden, Stadt", 
        "Frankfurt am Main, Stadt", 
        "Darmstadt, Wissenschaftsstadt",
        "Offenbach am Main, Stadt",
        "Wiesbaden, Landeshauptstadt",
        "Darmstadt-Dieburg",
        "Lahn-Dill-Kreis",
        "Kassel, documenta-Stadt",
        "Kassel, Stadt",
        "Bergstraße",
        "Darmstadt-Dieburg",
        "Groß-Gerau",
        "Hochtaunuskreis",
        "Main-Kinzig-Kreis",
        "Main-Taunus-Kreis",
        "Odenwaldkreis",
        "Offenbach",
        "Rheingau-Taunus-Kreis",
        "Schwalm-Eder-Kreis",
        "Wetteraukreis",
        "Werra-Meißner-Kreis",
        "Gießen",
        "Kassel",
        "Limburg-Weilburg",
        "Marburg-Biedenkopf",
        "Vogelsbergkreis",
        "Waldeck-Frankenberg",
        "Fulda",
        "Hersfeld-Rotenburg",
        "Kassel",
        "Schwalm-Eder-Kreis",
        "Werra-Meißner-Kreis"
    ],
    "Thüringen": [
        "Erfurt, Stadt", 
        "Jena, Stadt", 
        "Gera, Stadt",
        "Altenburger Land",
        "Eichsfeld",
        "Gotha",
        "Greiz",
        "Suhl, Stadt",
        "Weimar, Stadt",
        "Hildburghausen",
        "Ilm-Kreis",
        "Kyffhäuserkreis",
        "Nordhausen",
        "Saale-Holzland-Kreis",
        "Saale-Orla-Kreis",
        "Saalfeld-Rudolstadt",
        "Schmalkalden-Meiningen",
        "Sömmerda",
        "Sonneberg",
        "Unstrut-Hainich-Kreis",
        "Wartburgkreis",
        "Weimarer Land"
    ],
    "Rheinland-Pfalz": [
        "Mainz, Stadt", 
        "Ludwigshafen am Rhein, Stadt", 
        "Koblenz, kreisfreie Stadt",
        "Koblenz, Stadt",
        "Ahrweiler",
        "Altenkirchen",
        "Altenkirchen (Westerwald)",
        "Alzey-Worms",
        "Bad Dürkheim",
        "Bad Kreuznach",
        "Bernkastel-Wittlich",
        "Birkenfeld",
        "Cochem-Zell",
        "Donnersbergkreis",
        "Eifelkreis Bitburg-Prüm",
        "Frankenthal (Pfalz), kreisfreie Stadt",
        "Kaiserslautern, kreisfreie Stadt",
        "Landau in der Pfalz, kreisfreie Stadt",
        "Ludwigshafen am Rhein, kreisfreie Stadt",
        "Mainz, kreisfreie Stadt",
        "Neustadt an der Weinstraße, kreisfreie Stadt",
        "Pirmasens, kreisfreie Stadt",
        "Speyer, kreisfreie Stadt",
        "Worms, kreisfreie Stadt",
        "Zweibrücken, kreisfreie Stadt",
        "Mainz-Bingen",
        "Germersheim",
        "Kaiserslautern",
        "Kusel",
        "Mayen-Koblenz",
        "Neuwied",
        "Rhein-Hunsrück-Kreis",
        "Rhein-Lahn-Kreis",
        "Rhein-Pfalz-Kreis",
        "Südliche Weinstraße",
        "Südwestpfalz",
        "Trier-Saarburg",
        "Trier, kreisfreie Stadt",
        "Vulkaneifel",
        "Westerwaldkreis"
    ],
    "Baden-Württemberg": [
        "Stuttgart, Stadt", 
        "Mannheim, Stadt", 
        "Karlsruhe, Stadt", 
        "Freiburg im Breisgau, Stadt",
        "Stuttgart, Stadtkreis",
        "Heilbronn, Stadtkreis",
        "Heilbronn",
        "Mannheim, Stadtkreis",
        "Pforzheim, Stadtkreis",
        "Karlsruhe, Stadtkreis",
        "Hohenlohekreis",
        "Ulm, Stadtkreis",
        "Baden-Baden, Stadtkreis",
        "Karlsruhe, Stadtkreis",
        "Freiburg im Breisgau, Stadtkreis",
        "Heidelberg, Stadtkreis",
        "Heidelberg, Stadt",
        "Heilbronn, Stadt",
        "Pforzheim, Stadt",
        "Ulm, Stadt",
        "Alb-Donau-Kreis",
        "Baden-Baden",
        "Biberach",
        "Böblingen",
        "Bodenseekreis",
        "Breisgau-Hochschwarzwald",
        "Calw",
        "Emmendingen",
        "Enzkreis",
        "Esslingen",
        "Freudenstadt",
        "Göppingen",
        "Heidenheim",
        "Karlsruhe",
        "Konstanz",
        "Lörrach",
        "Ludwigsburg",
        "Main-Tauber-Kreis",
        "Neckar-Odenwald-Kreis",
        "Ortenaukreis",
        "Ostalbkreis",
        "Rastatt",
        "Ravensburg",
        "Rems-Murr-Kreis",
        "Reutlingen",
        "Rhein-Neckar-Kreis",
        "Rottweil",
        "Schwäbisch Hall",
        "Schwarzwald-Baar-Kreis",
        "Sigmaringen",
        "Tübingen",
        "Tuttlingen",
        "Waldshut",
        "Zollernalbkreis"
    ],
    "Bayern": [
        "München, Stadt", 
        "Nürnberg, Stadt", 
        "Augsburg, Stadt",
        "Ingolstadt",
        "München, Landeshauptstadt",
        "Bad Tölz-Wolfratshausen",
        "Landsberg am Lech",
        "Pfaffenhofen a.d.Ilm",
        "Landshut, Stadt",
        "Passau, Stadt",
        "Straubing",
        "Dingolfing-Landau",
        "Amberg",
        "Weiden i.d.OPf.",
        "Amberg-Sulzbach",
        "Neumarkt i.d.OPf.",
        "Neustadt a.d.Waldnaab",
        "Regensburg",
        "Bamberg, Stadt",
        "Bayreuth, Stadt",
        "Coburg, Stadt",
        "Hof, Stadt",
        "Forchheim",
        "Ansbach, Stadt",
        "Erlangen",
        "Nürnberg",
        "Schwabach",
        "Erlangen-Höchstadt",
        "Fürth",
        "Neustadt a.d.Aisch-Bad Windsheim",
        "Aschaffenburg, Stadt",
        "Schweinfurt, Stadt",
        "Rhön-Grabfeld",
        "Haßberge",
        "Kitzingen",
        "Miltenberg",
        "Main-Spessart",
        "Schweinfurt",
        "Würzburg",
        "Kaufbeuren",
        "Kempten (Allgäu)",
        "Memmingen",
        "Augsburg",
        "Dillingen a.d.Donau",
        "Neu-Ulm",
        "Lindau (Bodensee)",
        "Unterallgäu",
        "Rosenheim, Stadt",
        "Regensburg, Stadt",
        "Ingolstadt, Stadt",
        "Würzburg, Stadt",
        "Fürth, Stadt",
        "Erlangen, Stadt",
        "Bamberg",
        "Bayreuth",
        "Coburg",
        "Hof",
        "Ansbach",
        "Aschaffenburg",
        "Deggendorf",
        "Dillingen a.d. Donau",
        "Freyung-Grafenau",
        "Kelheim",
        "Landshut",
        "Passau",
        "Regen",
        "Rottal-Inn",
        "Straubing-Bogen",
        "Dachau",
        "Ebersberg",
        "Eichstätt",
        "Erding",
        "Freising",
        "Fürstenfeldbruck",
        "Garmisch-Partenkirchen",
        "Landsberg a.Lech",
        "Miesbach",
        "Mühldorf a.Inn",
        "München",
        "Neuburg-Schrobenhausen",
        "Pfaffenhofen a.d. Ilm",
        "Rosenheim",
        "Starnberg",
        "Traunstein",
        "Weilheim-Schongau",
        "Weißenburg-Gunzenhausen",
        "Aichach-Friedberg",
        "Altötting",
        "Bad Kissingen",
        "Berchtesgadener Land",
        "Cham",
        "Donau-Ries",
        "Günzburg",
        "Kronach",
        "Kulmbach",
        "Lichtenfels",
        "Neumarkt i.d. OPf.",
        "Neustadt a.d. Waldnaab",
        "Nürnberger Land",
        "Oberallgäu",
        "Ostallgäu",
        "Regen",
        "Roth",
        "Schwandorf",
        "Tirschenreuth",
        "Weiden i.d. OPf.",
        "Wunsiedel i.Fichtelgebirge"
    ],
    "Saarland": [
        "Saarbrücken, Stadt",
        "Regionalverband Saarbrücken",

        "Merzig-Wadern",
        "Neunkirchen",
        "Saarlouis",
        "Saarpfalz-Kreis",
        "St. Wendel"
    ]
}